blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/syu-kuri/valobot/discussions
    about: For general questions, please use GitHub Discussions instead of opening an issue.
